[package]
name = "screen"
version = "0.1.0"
authors = ["Lars Westermann <lars.westermann@tu-dresden.de>"]

[dependencies]
image = "0.23.8"
imageproc = "0.21.0"
ev3dev-lang-rust = { path = "../..", features = ["screen"] }
