[package]
name = "ev3dev-lang-rust"
version = "0.1.0"
authors = ["Lars Westermann <lars-westermann@live.de>"]

description = "C++ language bindings for ev3dev"
keywords = ["ev3", "ev3dev", "lego", "mindstorms"]
categories = ["api-bindings", "embedded", "hardware-support"]

license = "MIT"

[dependencies]
