[package]
name = "ev3dev-lang-rust"
version = "0.2.0"
authors = ["Lars Westermann <lars-westermann@live.de>"]

description = "Rust language bindings for ev3dev"
keywords = ["ev3", "ev3dev", "lego", "mindstorms"]
categories = ["api-bindings", "embedded", "hardware-support"]

license = "MIT"

repository = "https://github.com/pixix4/ev3dev-lang-rust"

[badges]
travis-ci = { repository = "pixix4/ev3dev-lang-rust", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
